@startuml
activate User
User -> UI: "add test /n CS2113T Finals /s 2020-12-01 1300 /e 2020-12-01 1400
activate UI
UI -> Controller: runLogic()
activate UI
activate Controller
Controller -> Model: add(userInput)
activate Controller
Model --> Controller
deactivate Controller
Controller -> Storage: refreshEvents()
activate Controller
activate Storage
Storage -> Storage: saveData()
activate Storage
Storage --> Storage
deactivate Storage
Storage --> Controller
deactivate Storage
deactivate Controller
Controller --> UI
deactivate Controller
UI --> User
deactivate UI
@enduml