@startuml

skinparam ParticipantPadding 10
skinparam BoxPadding 5

participant Main

box "UserInterface" #skyblue
participant UserInterface
end box

box "Controller" #LightSalmon
participant ControlManager
end box

Main -> UserInterface : runUI()
activate Main
activate UserInterface
UserInterface -> UserInterface : getUserCommand()
activate UserInterface
UserInterface --> UserInterface
deactivate UserInterface
UserInterface -> ControlManager : runLogic()
activate ControlManager
ControlManager -> ControlManager : refreshEvents()
activate ControlManager
ControlManager --> ControlManager
deactivate ControlManager
ControlManager -> ControlManager : refreshQuizzes()
activate ControlManager
ControlManager --> ControlManager
deactivate ControlManager
ControlManager --> UserInterface
deactivate ControlManager
UserInterface -> UserInterface : checkIfProgramEnds(:CommandType)
activate UserInterface
UserInterface --> UserInterface
deactivate UserInterface
deactivate ControlManager
UserInterface --> Main
deactivate UserInterface
deactivate Main

@enduml