@startuml
allowmixing
skinparam actorStyle awesome
skinparam rectangle {
    roundCorner 25
}
skinparam MinClassWidth 100
hide circle
hide members
scale 450 width
skinparam Class {
    BorderColor Azure
}
skinparam Shadowing false
skinparam Actor {
    BorderColor Olive
    BackgroundColor Khaki
}

actor user

rectangle #Azure {
    class UserInterface #SkyBlue {
    }
    class Model #YellowGreen {
    }
    class Controller #LightSalmon {
    }
    class Main #Silver {
    }
    class Storage #Tan {
    }
}

package Data <<File>> #LightSalmon {
}

user ..down> UserInterface
UserInterface -down[bold,#SkyBlue]-> Controller
Controller -[Bold,#LightSalmon]-> Model : manipulate data
Model --[bold,#YellowGreen]> UserInterface : update view
UserInterface <-[#Silver] Main : initialize
Main -up[#Silver]> Model : initialize
Main -right[#Silver]> Storage : initialize
Storage ..[#Peru]> Data
Controller -[bold,#LightSalmon]> Storage

@enduml