@startuml
hide footbox

-> ":EventStorageManager" : loadData(:ArrayList<String>)
activate ":EventStorageManager"
":EventStorageManager" -> ":EventListDecoder" : decodeEventList(:ArrayList<String>)
activate ":EventListDecoder"

loop number of strings
":EventListDecoder" -> ":EventListDecoder" : decodeEventFromString(:String)
activate ":EventListDecoder"
alt cca
":EventListDecoder" -> ":EventListDecoder" : parseCca(:String)
activate ":EventListDecoder"
":EventListDecoder" --> ":EventListDecoder" : :EventCca
deactivate ":EventListDecoder"
else tuition
":EventListDecoder" -> ":EventListDecoder" : parseTuition(:String)
activate ":EventListDecoder"
":EventListDecoder" --> ":EventListDecoder" : :EventTuition
deactivate ":EventListDecoder"
else class
":EventListDecoder" -> ":EventListDecoder" : parseClass(:String)
activate ":EventListDecoder"
":EventListDecoder" --> ":EventListDecoder" : :EventClass
deactivate ":EventListDecoder"
else test
":EventListDecoder" -> ":EventListDecoder" : parseTest(:String)
activate ":EventListDecoder"
":EventListDecoder" --> ":EventListDecoder" : :EventTest
deactivate ":EventListDecoder"
end alt
":EventListDecoder" --> ":EventListDecoder"
deactivate ":EventListDecoder"
":EventListDecoder" --> ":EventStorageManager" : :ArrayList<Event>
deactivate ":EventListDecoder"
end loop
<-- ":EventStorageManager" : :EventParameter
deactivate ":EventStorageManager"
@enduml