@startuml
hide footbox

-> ":EventStorageManager" : saveData(eventList)
activate ":EventStorageManager"
":EventStorageManager" -> ":EventListEncoder" : encodeEventList(eventList)
activate ":EventListEncoder"

loop number of events
":EventListEncoder" -> ":EventListEncoder" : encodeEventToString(event)
activate ":EventListEncoder" #salmon
":EventListEncoder" --> ":EventListEncoder" : data
deactivate ":EventListEncoder"
":EventListEncoder" --> ":EventStorageManager"
deactivate ":EventListEncoder"
end loop
<-- ":EventStorageManager"
deactivate ":EventStorageManager"

@enduml