@startuml

skinparam ParticipantPadding 10
skinparam SequenceGroup 200
skinparam BoxPadding 5
hide footbox

box "Controller" #LightSalmon
participant ":ListCommand"
end box

box "Model" #YellowGreen
participant ":QuizManager"
end box

box "UserInterface" #skyblue
participant ":UserInterface"
end box

":ListCommand" -> ":QuizManager" : execute()
activate ":ListCommand"
activate ":QuizManager"
":QuizManager" -> ":QuizManager" : list()
activate ":QuizManager" #DarkSalmon
alt empty ArrayList
    ":QuizManager" -> ":UserInterface" : showToUser()
    activate ":UserInterface"
    ":UserInterface" --> ":QuizManager"
    deactivate ":UserInterface"
    ":QuizManager" --> ":ListCommand"
else else
    loop until end of ArrayList
        ":QuizManager" -> ":UserInterface" : showToUser()
        activate ":UserInterface"
        ":UserInterface" --> ":QuizManager"
        deactivate ":UserInterface"
        ":QuizManager" --> ":QuizManager"
        deactivate ":QuizManager"
        |||
    end
    ":QuizManager" --> ":ListCommand"
    deactivate ":QuizManager"
    deactivate ":ListCommand"
end
@enduml