@startuml
hide footbox

box "Controller" #LightSalmon
participant ":ListCommand"
end box

box "Model" #YellowGreen
participant ":EventManager"
participant ":ListSchedule"
end box

box "UserInterface" #skyblue
participant ":UserInterface"
participant ":CalendarWeekRenderer"
end box

":ListCommand" -> ":EventManager" : execute()
activate ":ListCommand"
activate ":EventManager"
":EventManager" -> ":EventManager" : listSchedule()
activate ":EventManager" #Salmon
":EventManager" -> ":ListSchedule"** : constructor()
activate ":ListSchedule"
":ListSchedule" --> ":EventManager"
deactivate ":ListSchedule"
":EventManager" -> ":UserInterface" : printWeekSchedule(this)
activate ":UserInterface"
":UserInterface" -> ":CalendarWeekRenderer"** : constructor()
activate ":CalendarWeekRenderer"
":CalendarWeekRenderer" -> ":UserInterface"
deactivate ":CalendarWeekRenderer"
":UserInterface" --> ":EventManager"
deactivate ":UserInterface"
":EventManager" --> ":EventManager"
deactivate ":EventManager"
":EventManager" --> ":ListCommand"
deactivate
deactivate ":ListCommand"
destroy ":CalendarWeekRenderer"

@enduml