@startuml

skinparam ParticipantPadding 10
skinparam BoxPadding 5
hide footbox

box "Controller" #LightSalmon
participant ":ListCommand"
end box

box "Model" #YellowGreen
participant ":EventManager"
participant ":ListSchedule"
end box

box "UserInterface" #skyblue
participant ":UserInterface"
end box

":ListCommand" -> ":EventManager" : execute()
activate ":EventManager"
":EventManager" -> ":EventManager" : list()
activate ":EventManager" #DarkSalmon
":EventManager" -> ":ListSchedule" ** : constructor()
activate ":ListSchedule"
":ListSchedule" --> ":EventManager"
deactivate ":ListSchedule"
":EventManager" -> ":ListSchedule" : getPrintableEvents()
activate ":ListSchedule"
":ListSchedule" --> ":EventManager" : string array
deactivate ":ListSchedule"
":EventManager" -> ":UserInterface" : printArray()
activate ":UserInterface"
":UserInterface" --> ":EventManager"
deactivate ":UserInterface"
deactivate ":EventManager"
":EventManager" --> ":ListCommand"
deactivate ":EventManager"
destroy ":ListSchedule"

@enduml