@startuml

skinparam ParticipantPadding 10
skinparam BoxPadding 5
hide footbox

box "Storage" #YellowGreen
participant ":QuizStorageManager"
participant ":QuizListDecoder"
end box

box "File" #orange
participant ":File"
end box

-> ":QuizStorageManager" : loadData()
activate ":QuizStorageManager"
":QuizStorageManager" -> ":QuizStorageManager" : createDataFile()
activate ":QuizStorageManager" #salmon
":QuizStorageManager" -> ":File" ** : constructor()
activate ":File"
":File" --> ":QuizStorageManager"
deactivate ":File"
":QuizStorageManager" -> ":File" : createNewFile()
activate ":File"
":File" --> ":QuizStorageManager" : fileCreated
deactivate ":File"

opt !fileCreated
":QuizStorageManager" -> ":QuizListDecoder" : decodeQuizList()
activate ":QuizListDecoder"
":QuizListDecoder" -> ":QuizListDecoder" : decodeQuizFromString()
activate ":QuizListDecoder" #salmon
":QuizListDecoder" --> ":QuizListDecoder" : Quiz
deactivate ":QuizListDecoder"
":QuizListDecoder" --> ":QuizStorageManager" : decodedQuizzes
deactivate ":QuizListDecoder"
<-- ":QuizStorageManager" : decodedQuizzes
deactivate ":QuizStorageManager"
end opt

<-- ":QuizStorageManager" : new ArrayList<>()
deactivate ":QuizStorageManager"
destroy ":File"

@enduml