@startuml
UserInterface -> ControlManager: runLogic()
ControlManager -> CommandParser: extractCommand()

CommandParser --> ControlManager: return command type

ControlManager -> CommandFactory: generateActionableCommand()
CommandFactory --> ControlManager: return actionable command

ControlManager -> ModelParser: extractModel()
ModelParser --> ControlManager: return model type

ControlManager -> ModelExtractor: retrieveModel()
ModelExtractor --> ControlManager: return model

ControlManager -> AddCommand: execute()
AddCommand -> DataManager: add()
activate DataManager
DataManager -> DataManager: getClassStatement()
activate DataManager
DataManager -> UserInterface: showToUser()

UserInterface --> DataManager
DataManager --> AddCommand
deactivate DataManager
deactivate DataManager
AddCommand --> ControlManager
ControlManager --> UserInterface: return command type

@enduml