@startuml

skinparam ParticipantPadding 10
skinparam BoxPadding 5

box "Controller" #LightSalmon
participant ControlManager
participant CommandParser
participant HelpCommand
end box

box "UserInterface" #skyblue
participant UserInterface
end box


ControlManager -> CommandParser: extractCommand()
activate ControlManager
activate CommandParser
CommandParser --> ControlManager: return command type
deactivate CommandParser

ControlManager -> HelpCommand: execute()
activate HelpCommand
HelpCommand -> HelpCommand: handleHelp()
activate HelpCommand
deactivate HelpCommand

HelpCommand -> UserInterface: showToUser()
activate UserInterface
UserInterface --> HelpCommand
deactivate UserInterface
HelpCommand --> ControlManager

deactivate ControlManager
deactivate HelpCommand

@enduml