@startuml

ListCommand -> EventManager : execute()
activate EventManager
EventManager -> EventManager : listSchedule()
activate EventManager
EventManager -> ListSchedule** : constructor()
activate ListSchedule
ListSchedule --> EventManager
deactivate ListSchedule
EventManager -> UserInterface : printWeekSchedule(this)
activate UserInterface
UserInterface -> CalendarWeekRenderer** : constructor()
activate CalendarWeekRenderer
CalendarWeekRenderer -> UserInterface
destroy CalendarWeekRenderer
deactivate UserInterface
UserInterface --> EventManager
deactivate EventManager
EventManager --> ListCommand

@enduml